// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ptxinwtjmipcvmchxqdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0eGlud3RqbWlwY3ZtY2h4cWR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NzYzMzgsImV4cCI6MjA3MjA1MjMzOH0.6kzVXM3Z55iJhiM_KNYCNUXAofBeTeeFFqTOgDHaQH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);